# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://foster.engineer
title: Eli Foster
email: elijam124@gmail.com
author: Eli Foster
description: > # "Write an awesome description for your new site here. 
  Portfolio website for Eli Foster, Electrical Engineer based out of Bucknell University.

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/Foster-05
  - title: linkedin
    url: https://www.linkedin.com/in/eli-foster-bucknellu/
